###################################################################
# CNN synthesis SDC - fully expanded format for ZenSyn compatibility
###################################################################
set sdc_version 2.1
set_units -time ns -resistance kOhm -capacitance pF -power mW -voltage V -current mA
set_wire_load_mode segmented
set_max_transition 3 [current_design]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports clk]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports rst_n]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports start]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports img_wr_en]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_addr[4]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_addr[3]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_addr[2]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_addr[1]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_addr[0]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[79]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[78]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[77]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[76]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[75]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[74]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[73]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[72]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[71]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[70]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[69]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[68]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[67]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[66]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[65]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[64]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[63]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[62]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[61]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[60]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[59]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[58]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[57]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[56]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[55]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[54]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[53]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[52]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[51]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[50]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[49]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[48]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[47]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[46]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[45]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[44]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[43]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[42]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[41]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[40]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[39]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[38]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[37]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[36]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[35]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[34]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[33]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[32]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[31]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[30]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[29]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[28]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[27]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[26]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[25]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[24]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[23]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[22]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[21]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[20]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[19]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[18]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[17]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[16]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[15]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[14]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[13]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[12]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[11]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[10]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[9]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[8]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[7]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[6]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[5]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[4]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[3]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[2]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[1]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports {img_wr_row_data[0]}]
set_driving_cell -lib_cell PO8W -pin PAD [get_ports img_wr_commit]
set_load -pin_load 4.37 [get_ports busy]
set_load -pin_load 4.37 [get_ports done]
set_load -pin_load 4.37 [get_ports img_wr_ready]
set_load -pin_load 4.37 [get_ports out_stream_valid]
set_load -pin_load 4.37 [get_ports {out_stream_data[63]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[62]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[61]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[60]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[59]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[58]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[57]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[56]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[55]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[54]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[53]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[52]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[51]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[50]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[49]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[48]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[47]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[46]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[45]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[44]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[43]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[42]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[41]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[40]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[39]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[38]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[37]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[36]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[35]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[34]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[33]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[32]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[31]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[30]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[29]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[28]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[27]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[26]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[25]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[24]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[23]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[22]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[21]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[20]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[19]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[18]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[17]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[16]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[15]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[14]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[13]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[12]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[11]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[10]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[9]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[8]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[7]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[6]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[5]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[4]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[3]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[2]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[1]}]
set_load -pin_load 4.37 [get_ports {out_stream_data[0]}]
set_ideal_network [get_ports rst_n]
create_clock [get_ports clk]  -period 10  -waveform {0 5}
# 网络延迟偏小：由 0.3 ns 修改为 2ns
set_clock_latency 2.0  [get_clocks clk]
# 源延迟偏大: 由 4ns 修改为 1.5 ns
set_clock_latency -source 1.5  [get_clocks clk]
set_clock_uncertainty 0.5  [get_clocks clk]
set_clock_transition -min -fall 0.2 [get_clocks clk]
set_clock_transition -min -rise 0.2 [get_clocks clk]
set_clock_transition -max -fall 0.2 [get_clocks clk]
set_clock_transition -max -rise 0.2 [get_clocks clk]
set_input_delay -clock clk  -max 5  [get_ports rst_n]
set_input_delay -clock clk  -max 5  [get_ports start]
set_input_delay -clock clk  -max 5  [get_ports img_wr_en]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_addr[4]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_addr[3]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_addr[2]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_addr[1]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_addr[0]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[79]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[78]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[77]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[76]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[75]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[74]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[73]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[72]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[71]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[70]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[69]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[68]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[67]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[66]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[65]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[64]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[63]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[62]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[61]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[60]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[59]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[58]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[57]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[56]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[55]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[54]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[53]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[52]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[51]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[50]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[49]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[48]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[47]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[46]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[45]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[44]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[43]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[42]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[41]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[40]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[39]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[38]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[37]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[36]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[35]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[34]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[33]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[32]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[31]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[30]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[29]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[28]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[27]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[26]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[25]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[24]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[23]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[22]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[21]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[20]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[19]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[18]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[17]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[16]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[15]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[14]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[13]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[12]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[11]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[10]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[9]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[8]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[7]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[6]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[5]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[4]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[3]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[2]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[1]}]
set_input_delay -clock clk  -max 5  [get_ports {img_wr_row_data[0]}]
set_input_delay -clock clk  -max 5  [get_ports img_wr_commit]
set_output_delay -clock clk  -max 5  [get_ports busy]
set_output_delay -clock clk  -max 5  [get_ports done]
set_output_delay -clock clk  -max 5  [get_ports img_wr_ready]
set_output_delay -clock clk  -max 5  [get_ports out_stream_valid]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[63]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[62]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[61]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[60]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[59]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[58]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[57]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[56]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[55]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[54]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[53]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[52]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[51]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[50]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[49]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[48]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[47]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[46]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[45]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[44]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[43]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[42]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[41]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[40]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[39]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[38]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[37]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[36]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[35]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[34]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[33]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[32]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[31]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[30]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[29]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[28]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[27]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[26]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[25]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[24]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[23]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[22]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[21]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[20]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[19]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[18]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[17]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[16]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[15]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[14]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[13]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[12]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[11]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[10]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[9]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[8]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[7]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[6]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[5]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[4]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[3]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[2]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[1]}]
set_output_delay -clock clk  -max 5  [get_ports {out_stream_data[0]}]
